"""add submission_logs table

Revision ID: cec206ee2207
Revises: b2ccdce3fa9d
Create Date: 2025-12-29 22:00:05.504814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cec206ee2207'
down_revision: Union[str, Sequence[str], None] = 'b2ccdce3fa9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create submission_logs table
    op.create_table('submission_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('problem_id', sa.Integer(), nullable=False),
        sa.Column('verdict', sa.String(), nullable=False),
        sa.Column('execution_time', sa.Float(), nullable=True),
        sa.Column('timeout_flag', sa.Boolean(), nullable=True),
        sa.Column('payload_size', sa.Integer(), nullable=True),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['problem_id'], ['course_problems.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_logs_id'), 'submission_logs', ['id'], unique=False)
    op.create_index(op.f('ix_submission_logs_problem_id'), 'submission_logs', ['problem_id'], unique=False)
    op.create_index(op.f('ix_submission_logs_user_id'), 'submission_logs', ['user_id'], unique=False)
    
    # Other auto-detected cleanups
    op.drop_constraint('unique_course_language', 'courses', type_='unique')
    op.drop_index('ix_courses_language', table_name='courses')
    op.create_index(op.f('ix_courses_language'), 'courses', ['language'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop submission_logs table
    op.drop_index(op.f('ix_submission_logs_user_id'), table_name='submission_logs')
    op.drop_index(op.f('ix_submission_logs_problem_id'), table_name='submission_logs')
    op.drop_index(op.f('ix_submission_logs_id'), table_name='submission_logs')
    op.drop_table('submission_logs')
    
    # Revert courses index
    op.drop_index(op.f('ix_courses_language'), table_name='courses')
    op.create_index('ix_courses_language', 'courses', ['language'], unique=False)
    op.create_unique_constraint('unique_course_language', 'courses', ['language'])
    # ### end Alembic commands ###
