"""add validation_policy to course_problems

Revision ID: f2fe8f7d730e
Revises: cec206ee2207
Create Date: 2025-12-30 10:57:41.759099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2fe8f7d730e'
down_revision: Union[str, Sequence[str], None] = 'cec206ee2207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('behavior_logs', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'LOW'::character varying"))
    op.alter_column('course_problem_test_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('course_problems', sa.Column('validation_policy', sa.JSON(), nullable=True))
    op.alter_column('course_problems', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('unique_course_language'), 'courses', type_='unique')
    op.drop_index(op.f('ix_courses_language'), table_name='courses')
    op.create_index(op.f('ix_courses_language'), 'courses', ['language'], unique=True)
    op.alter_column('problems', 'is_test_problem',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('problems', 'starter_code')
    op.drop_column('scheduled_tests', 'problem_ids')
    op.alter_column('submissions', 'is_test_submission',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('test_problems', 'order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_test_problems_problem_id'), table_name='test_problems')
    op.drop_index(op.f('ix_test_problems_test_id'), table_name='test_problems')
    op.create_index(op.f('ix_test_problems_id'), 'test_problems', ['id'], unique=False)
    op.alter_column('user_course_progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_course_progress', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_test_problems_id'), table_name='test_problems')
    op.create_index(op.f('ix_test_problems_test_id'), 'test_problems', ['test_id'], unique=False)
    op.create_index(op.f('ix_test_problems_problem_id'), 'test_problems', ['problem_id'], unique=False)
    op.alter_column('test_problems', 'order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('submissions', 'is_test_submission',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('scheduled_tests', sa.Column('problem_ids', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.add_column('problems', sa.Column('starter_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('problems', 'is_test_problem',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_courses_language'), table_name='courses')
    op.create_index(op.f('ix_courses_language'), 'courses', ['language'], unique=False)
    op.create_unique_constraint(op.f('unique_course_language'), 'courses', ['language'], postgresql_nulls_not_distinct=False)
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('course_problems', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('course_problems', 'validation_policy')
    op.alter_column('course_problem_test_cases', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('behavior_logs', 'severity',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'LOW'::character varying"))
    op.alter_column('admin_audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
